"""Accountability Agent (agents.md §2).

The system's "eyes on the ground." Two cleanly separated halves:

1. ``decide_escalation`` — **pure, deterministic Python** over ``checkin_history``,
   ``last_checkin_at`` and ``escalation_level``. It implements the exact 5-row
   escalation ladder from agents.md §2 and decides *which rung applies*,
   the new ``escalation_level``, the ``pending_event`` to emit, and whether a
   voice call is warranted. **The LLM never makes this decision.**

2. The LLM is called **only** to write the user-facing text (notification copy, or
   the level-2 voice-call script), under a system prompt that enforces the
   "warm, specific, references the actual plan item, never frames a miss as
   failure" tone from §2's "important design choice."

This mirrors the Game Master / Engine split: judgment (tone, wording) stays
probabilistic; guaranteed behaviour (which rung, what event) stays deterministic.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

from agents.llm import build_chat_model
from state import AgentEvent, CheckIn, EventType, UserState

Rung = Literal["on_time", "one_miss", "two_misses", "three_plus", "comeback"]


@dataclass(frozen=True)
class EscalationDecision:
    """The deterministic verdict for one check-in evaluation."""

    rung: Rung
    escalation_level: int
    event_type: Optional[EventType]
    place_voice_call: bool


# --------------------------------------------------------------------------- #
# Deterministic decision logic — the escalation ladder (agents.md §2)         #
# --------------------------------------------------------------------------- #
def _trailing_misses(history: list[CheckIn]) -> int:
    """Count consecutive missed (``completed`` is False) check-ins from newest."""
    misses = 0
    for ci in reversed(history):
        if ci.get("completed"):
            break
        misses += 1
    return misses


def decide_escalation(
    checkin_history: list[CheckIn],
    last_checkin_at: datetime | None,
    escalation_level: int,
) -> EscalationDecision:
    """Decide which escalation rung applies. Pure function — no LLM, no I/O.

    Maps directly to the 5-row ladder in agents.md §2:

    | rung        | condition                              | level | event             |
    |-------------|----------------------------------------|-------|-------------------|
    | on_time     | latest check-in completed (was calm)   | 0     | streak_maintained |
    | one_miss    | exactly 1 trailing miss                | (same)| None              |
    | two_misses  | exactly 2 trailing misses              | 1     | None              |
    | three_plus  | 3+ trailing misses                     | 2     | None + voice call |
    | comeback    | latest completed after being escalated | 0     | comeback_detected |

    Misses emit no ``pending_event``: the world rewards progress, never punishes a
    gap (a miss only produces a warm notification, generated by the node).
    """
    history = sorted(checkin_history, key=lambda c: c.get("timestamp") or datetime.min)
    if not history:
        # Nothing to evaluate; leave escalation untouched, emit nothing.
        return EscalationDecision("on_time", escalation_level, None, False)

    latest = history[-1]

    if latest.get("completed"):
        if escalation_level > 0:
            # Resumed after a gap — acknowledge warmly, reset the ladder.
            return EscalationDecision("comeback", 0, "comeback_detected", False)
        return EscalationDecision("on_time", 0, "streak_maintained", False)

    misses = _trailing_misses(history)
    if misses >= 3:
        return EscalationDecision("three_plus", 2, None, True)
    if misses == 2:
        return EscalationDecision("two_misses", 1, None, False)
    return EscalationDecision("one_miss", escalation_level, None, False)


# --------------------------------------------------------------------------- #
# LLM-only structured output — the user-facing text                           #
# --------------------------------------------------------------------------- #
class Intervention(BaseModel):
    message: str = Field(
        description=(
            "Warm, specific message that references the actual plan item. For a "
            "voice call this is the spoken script. NEVER frames a missed check-in "
            "as failure."
        )
    )


_TONE_SYSTEM = (
    "You are Tsumiki's Accountability voice. You are calm, never guilt-driven. "
    "Always reference the user's actual plan item and goal. Treat any gap as "
    "information to plan around, NEVER as a moral failure — do not say 'you broke "
    "your streak' or anything punitive. Be brief and human."
)

# What each rung asks the model to produce. The rung itself is decided
# deterministically above; only the wording is the model's job.
_RUNG_BRIEF: dict[Rung, str] = {
    "one_miss": (
        "The user missed today's session. Offer a shorter version tonight. One or "
        "two warm sentences."
    ),
    "two_misses": (
        "The user has missed two sessions in a row. Gently check in ('everything "
        "okay?'), reference how long it's been. No pressure."
    ),
    "three_plus": (
        "Write a short, warm VOICE-CALL script. The user has missed several "
        "sessions. Reference their goal and streak history with care; invite them "
        "back without any guilt."
    ),
    "comeback": (
        "The user just came back after a gap. Acknowledge their return warmly and "
        "positively. Absolutely no 'you broke your streak' messaging."
    ),
}


class AccountabilityAgent:
    """LangGraph node wrapping the deterministic ladder + tone-only LLM call."""

    def __init__(self, model: str | None = None, llm: Any | None = None) -> None:
        self._model = model
        self._llm = llm

    @property
    def llm(self) -> Any:
        if self._llm is None:
            self._llm = build_chat_model(self._model)
        return self._llm

    def _generate_message(self, state: UserState, decision: EscalationDecision) -> str:
        goal = state.get("active_goal") or {}
        plan = state.get("plan") or []
        next_item = plan[0]["description"] if plan else "your next session"
        brief = _RUNG_BRIEF[decision.rung]
        human = (
            f"Goal: {goal.get('title')} (domain: {goal.get('domain')}).\n"
            f"Current streak: {state.get('streak', 0)}.\n"
            f"Relevant plan item: {next_item}.\n\n{brief}"
        )
        structured = self.llm.with_structured_output(Intervention)
        result: Intervention = structured.invoke(
            [("system", _TONE_SYSTEM), ("human", human)]
        )
        return result.message

    @staticmethod
    def _make_event(state: UserState, etype: EventType) -> AgentEvent:
        goal = state.get("active_goal") or {}
        # Goal carries no id of its own (IDs live in the relational store); the
        # title is used as a human-readable str reference for the event payload.
        return AgentEvent(
            type=etype,
            goal_id=goal.get("title", ""),
            difficulty="medium",  # a sensible default; Game Master refines this
            timestamp=state.get("last_checkin_at") or datetime.now(),
        )

    def __call__(self, state: UserState) -> dict:
        decision = decide_escalation(
            state.get("checkin_history") or [],
            state.get("last_checkin_at"),
            state.get("escalation_level", 0),
        )

        updates: dict = {"escalation_level": decision.escalation_level}

        # Only the wording is the LLM's job, and only when there is something to
        # say (every rung except a plain on-time streak).
        if decision.rung != "on_time":
            updates["intervention_message"] = self._generate_message(state, decision)

        if decision.event_type is not None:
            updates["pending_event"] = self._make_event(state, decision.event_type)

        # The voice call itself (Vapi) is wired in the Voice layer (§5); here we
        # only record that the deterministic ladder called for one.
        if decision.place_voice_call:
            updates["place_voice_call"] = True

        return updates
